//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haber_portalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int KayitId { get; set; }
        public int KayitHaberId { get; set; }
        public int KayitKatId { get; set; }
    }
}
